# Generated by Django 4.0.6 on 2022-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdatatable',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
