# Generated by Django 4.0.6 on 2022-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ticketdatatable_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdatatable',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='ticketdatatable',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
