# Generated by Django 3.2.10 on 2022-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_ticketdatatable_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdatatable',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
