# Generated by Django 3.2.10 on 2022-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ticketdatatable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdatatable',
            name='image',
        ),
    ]
