# Generated by Django 3.2.10 on 2022-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ticketdatatable_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdatatable',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='ticketdatatable',
            name='imageName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
