# Generated by Django 3.2.6 on 2022-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ticketoperationtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdatatable',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='ticketdatatable',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='ticketdatatable',
            name='domain',
            field=models.CharField(default='none', max_length=255, null=True),
        ),
    ]
