# Generated by Django 4.0.6 on 2022-08-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='per_page',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
